// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Entities.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BookedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookedByUserId");

                    b.HasIndex("ChildId");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("TimeSlotId", "BookingDate");

                    b.HasIndex("TimeSlotId", "ChildId");

                    b.HasIndex("TimeSlotId", "StudentId");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Booking_StudentOrChild", "((StudentId IS NOT NULL AND ChildId IS NULL) OR (StudentId IS NULL AND ChildId IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("Domain.Models.Entities.Children.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchoolGrade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Domain.Models.Entities.JoinEntities.TimeSlotSubject", b =>
                {
                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("TimeSlotId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TimeSlotSubjects");
                });

            modelBuilder.Entity("Domain.Models.Entities.JoinEntities.VolunteerSubject", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("integer");

                    b.HasKey("VolunteerId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("VolunteerSubjects");
                });

            modelBuilder.Entity("Domain.Models.Entities.Subjects.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.Models.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.Entities.Venues.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("RecurringEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RecurringStartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SpecificDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VenueId");

                    b.HasIndex("VenueId", "DayOfWeek");

                    b.HasIndex("VenueId", "SpecificDate");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("Domain.Models.Entities.Venues.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CoordinatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("CoordinatorId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("Domain.Models.Entities.Volunteers.VolunteerApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByCoordinatorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAt");

                    b.HasIndex("ReviewedByCoordinatorId");

                    b.HasIndex("VenueId", "Status");

                    b.HasIndex("VolunteerId", "Status");

                    b.ToTable("VolunteerApplications");
                });

            modelBuilder.Entity("Domain.Models.Entities.Volunteers.VolunteerProfile", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("MaxHoursPerWeek")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreferredVenueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("VolunteerId");

                    b.HasIndex("PreferredVenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("VolunteerProfiles");
                });

            modelBuilder.Entity("Domain.Models.Entities.Volunteers.VolunteerShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAttended")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurrenceEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurrenceStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("TimeSlotId", "VolunteerId")
                        .IsUnique();

                    b.HasIndex("VolunteerId", "OccurrenceStartUtc");

                    b.ToTable("VolunteerShifts");
                });

            modelBuilder.Entity("Domain.Models.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Domain.Models.Entities.Bookings.Booking", b =>
                {
                    b.HasOne("Domain.Models.Entities.Users.User", "BookedByUser")
                        .WithMany("BookingsCreated")
                        .HasForeignKey("BookedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Entities.Children.Child", "Child")
                        .WithMany("Bookings")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.Entities.Users.User", "Student")
                        .WithMany("BookingsAsStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.Entities.Venues.TimeSlot", "TimeSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookedByUser");

                    b.Navigation("Child");

                    b.Navigation("Student");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("Domain.Models.Entities.Children.Child", b =>
                {
                    b.HasOne("Domain.Models.Entities.Users.User", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Models.Entities.JoinEntities.TimeSlotSubject", b =>
                {
                    b.HasOne("Domain.Models.Entities.Subjects.Subject", "Subject")
                        .WithMany("TimeSlotSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Entities.Venues.TimeSlot", "TimeSlot")
                        .WithMany("Subjects")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("Domain.Models.Entities.JoinEntities.VolunteerSubject", b =>
                {
                    b.HasOne("Domain.Models.Entities.Subjects.Subject", "Subject")
                        .WithMany("VolunteerSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Entities.Users.User", "Volunteer")
                        .WithMany("VolunteerSubjects")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Domain.Models.Entities.Venues.TimeSlot", b =>
                {
                    b.HasOne("Domain.Models.Entities.Venues.Venue", "Venue")
                        .WithMany("TimeSlots")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Domain.Models.Entities.Venues.Venue", b =>
                {
                    b.HasOne("Domain.Models.Entities.Users.User", "Coordinator")
                        .WithMany("CoordinatedVenues")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordinator");
                });

            modelBuilder.Entity("Domain.Models.Entities.Volunteers.VolunteerApplication", b =>
                {
                    b.HasOne("Domain.Models.Entities.Users.User", "ReviewedByCoordinator")
                        .WithMany("ReviewedVolunteerApplications")
                        .HasForeignKey("ReviewedByCoordinatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Entities.Venues.Venue", "Venue")
                        .WithMany("VolunteerApplications")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Entities.Users.User", "Volunteer")
                        .WithMany("VolunteerApplications")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReviewedByCoordinator");

                    b.Navigation("Venue");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Domain.Models.Entities.Volunteers.VolunteerProfile", b =>
                {
                    b.HasOne("Domain.Models.Entities.Venues.Venue", "PreferredVenue")
                        .WithMany()
                        .HasForeignKey("PreferredVenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Entities.Venues.Venue", null)
                        .WithMany("PreferredByVolunteers")
                        .HasForeignKey("VenueId");

                    b.HasOne("Domain.Models.Entities.Users.User", "Volunteer")
                        .WithOne("VolunteerProfile")
                        .HasForeignKey("Domain.Models.Entities.Volunteers.VolunteerProfile", "VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreferredVenue");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Domain.Models.Entities.Volunteers.VolunteerShift", b =>
                {
                    b.HasOne("Domain.Models.Entities.Venues.TimeSlot", "TimeSlot")
                        .WithMany("VolunteerShifts")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Entities.Users.User", "Volunteer")
                        .WithMany("VolunteerShifts")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimeSlot");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Domain.Models.Entities.Children.Child", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Domain.Models.Entities.Subjects.Subject", b =>
                {
                    b.Navigation("TimeSlotSubjects");

                    b.Navigation("VolunteerSubjects");
                });

            modelBuilder.Entity("Domain.Models.Entities.Users.User", b =>
                {
                    b.Navigation("BookingsAsStudent");

                    b.Navigation("BookingsCreated");

                    b.Navigation("Children");

                    b.Navigation("CoordinatedVenues");

                    b.Navigation("ReviewedVolunteerApplications");

                    b.Navigation("VolunteerApplications");

                    b.Navigation("VolunteerProfile");

                    b.Navigation("VolunteerShifts");

                    b.Navigation("VolunteerSubjects");
                });

            modelBuilder.Entity("Domain.Models.Entities.Venues.TimeSlot", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Subjects");

                    b.Navigation("VolunteerShifts");
                });

            modelBuilder.Entity("Domain.Models.Entities.Venues.Venue", b =>
                {
                    b.Navigation("PreferredByVolunteers");

                    b.Navigation("TimeSlots");

                    b.Navigation("VolunteerApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
